explain: |md
  AutoPM Architecture Overview
| {
  near: top-center
}

linear: Linear.app {
  shape: cloud
}
human: {
  shape: person
}
human -> ChatGPT Plugin: Conversational interface\nto Linear tasks.
ChatGPT Plugin -> AutoPM: OpenAPI Natural Language Interface

AutoPM -> linear: Task storage, priorization
human -> linear: Manual operations in Linear

linear -> AutoPM: webhooks

AutoPM: {
		AgentRouter {
				explain: |md
				Selects appropriate agent for some task.
				|
		}
  AgentRouter <-> vdb: Used for building context during \ntask creation, breakdown, prioritization.
  vdb: AutoPM \nVector DB {
    shape: cylinder
  }

  AgentRouter -> GPT4
  AgentRouter -> Langchain Agent
  AgentRouter -> AutoGPT Agent
  Langchain Agent -> Langchain Agent
  AutoGPT Agent -> AutoGPT Agent
}
